wandb_version: 1

batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 50
gradient_accumulation_steps:
  desc: null
  value: 6
learning_rate:
  desc: null
  value: 0.00011698484063436518
weight_decay:
  desc: null
  value: 0.6
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.33.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698665577.050882
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 100
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 100
      3:
      - 2
      - 23
      - 37
      4: 3.10.13
      5: 0.15.12
      6: 4.33.1
      8:
      - 5
      13: linux-x86_64
