wandb_version: 1

batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 50
gradient_accumulation_steps:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 6.219005913899588e-05
weight_decay:
  desc: null
  value: 0.6
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.33.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698648830.83789
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 2
      - 23
      - 37
      4: 3.8.18
      5: 0.15.12
      6: 4.33.1
      8:
      - 5
      13: linux-x86_64
